[env:esp32-wroom-32e]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=0

; Libraries
lib_deps =
    AsyncTCP
    ESPAsyncWebServer

; Upload protocol
upload_protocol = esptool

; Monitor output
monitor_filters = esp32_exception_decoder

; File system (LittleFS)
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L

; Partition scheme
board_build.partitions = default.csv
